# Generated by Django 5.2.14 on 2026-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxway_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
