# Generated by Django 5.2.14 on 2026-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxway_users', '0002_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
