# Generated by Django 5.2.14 on 2026-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxway_users', '0003_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Buyurtma Mahsuloti', 'verbose_name_plural': 'Buyurtma Mahsulotlari'},
        ),
    ]
